### ISSUE TITLE
Uh Deepfrying used as a WMD

### ISSUE THREAD

**Issue by subaruuuu123332** [jaw-sh/tgstation#20]
Issue reported from  Round ID: [417](https://scrubby.melonmesa.com/round/417) (Kiwi Station 13] [MRP] [EU] [English])

Reporting client version: 513.1536

When you put cooking oil that is boiling into a firefighting backpack it doesn't burn someone when its sprayed onto a person, but when you throw a beaker at someone with boiling cooking oil it burns them

**Comment by jaw-sh** [comment]
I don't think this is a bug mate.
