### ISSUE TITLE
/tg/ Shit PR mega list from disgruntled old fags

### ISSUE THREAD

**Issue by Ty-the-Smonk** [jaw-sh/tgstation#7]
Read Title
Im going to post the PR and a short description and why its dumb

### SLIME SECTION - AKA entirely my complaints because im a slimefag

[https://github.com/tgstation/tgstation/pull/44358](url) - Nurse Spider removal from Gold Extracts, Spiders at this point got a PR that made them obey their creators and their children also obey them so there really isnt really a reason to have armies be exclusive to antag

[https://github.com/tgstation/tgstation/pull/45800](url) - Bolt of death removal from Xenobio Magicarps, Magicarps of death are bullshit yes but they also are the easiest death to come back from, also death carps are just fun

[https://github.com/tgstation/tgstation/pull/49508](url) - Bolt of Change removal from Xenobio Magicarps, Changebolt was removed because """balance""" and that it could strip items locked to space ninja and other antags also armies of lesser drakes (chance is so fucking rare ive only gotten the drake once)

[https://github.com/tgstation/tgstation/pull/54198](url) - Yellow Slime Nerf, Yellow cores are now fucking useless and there is no reason to go for them, they became a side grade to BS cells.

[https://github.com/tgstation/tgstation/pull/46423](url) - Slime Mutagen nerf, Basically 1u of mutagen cant ligger you anymore and thats not fun, using these as makeshift tasers was always a good time

NO PR NUMBER - Removal of Xenobio Headslugs from the gold pool, I cant find the PR for the life of me, but Xenolings were a staple of the Xenobio any% category and the devs removed it, BRING BACK THE XENOLINGS

### Stupid General Shit - Oldfag complaints that arent mine

[https://github.com/tgstation/tgstation/pull/42386](url) - separated chemicals, this trait was usually just used for bombs but you could do all sorts of shit with it, got removed due to meta

[https://github.com/tgstation/tgstation/pull/41068](url) - Slips knockdown instead of stun, Direct clown nerf and an afront to god

[https://github.com/tgstation/tgstation/pull/45316](url) - Hivemind removal, Hivemind while janky as shit was very fun, it was removed due to it not being maintained anymore

[https://github.com/tgstation/tgstation/pull/45609](url) - Rwindows are now harder to get rid of than most walls and need a full toolkit, Really dumb buff since we have plasmaglass and other shit like it, there is no reason to use them if its THIS stronk

[https://github.com/tgstation/tgstation/pull/54759](url) - Cargo High bounty request removal, the bounty removal pr will be down the line from here so ill give my reasoning there

[https://github.com/tgstation/tgstation/pull/54029](url) - Bounty removal, Bounties were good content for cargo and now its given to the dogs

[https://github.com/tgstation/tgstation/pull/50465](url) - R&D console is in the RD office, Why the fuck do normal scientist not have access to one of the most important things in the game what the fuck

[https://github.com/tgstation/tgstation/pull/50384](url) - RnD console screwing, Check Reason above ^

[https://github.com/tgstation/tgstation/pull/49899](url) - RnD shit moved to the bridge, Check Reason above ^

[https://github.com/tgstation/tgstation/pull/53059](url) - Blood contract removal, dont know much about it personally, some oldfags wanted it on the list

[https://github.com/tgstation/tgstation/pull/53276](url) - Standard borg module removal, This is dumb for the same reasons the sec borg removal was dumb, Standard borgs are fun

[https://github.com/tgstation/tgstation/pull/53982](url) - Disco Inferno shuttle removal, Dying to inevitable burning at the shuttle is always a good time

[https://github.com/tgstation/tgstation/pull/53790](url) - Hilbert removal because it runtimes like a whore, Hilbert was one of the coolest ruin items in the game and they just yeeted it 

[https://github.com/tgstation/tgstation/pull/45377](url) - Baton rework, Old stuns were better

[https://github.com/tgstation/tgstation/pull/44216](url) - HoS gun taser replaced with Ion mode, HOS being the only motherfucker with a taser was a good time

[https://github.com/tgstation/tgstation/pull/42930](url) - War on Stuns 1, Old stuns were better

[https://github.com/tgstation/tgstation/pull/52880](url) - Hiero club no longer is attacking, Miner loot nerf to miners who decided to take on a boss, dumb nerf

[https://github.com/tgstation/tgstation/pull/45232](url) - """fix""" to plasma bridges, Was considered a feature until this guy said it was a bug

[https://github.com/tgstation/tgstation/pull/18951](url) - Sling removal, Slings were fun

### DEVIL - Old and shitty but here for nostalgia sake
These two are Devil in its entirety, Devil was extremely RP focused and could probably be reworked easily 
[https://github.com/tgstation/tgstation/pull/54356](url)
[https://github.com/tgstation/tgstation/pull/53612](url)

### ANNE PRS - Worst Coder

[https://github.com/tgstation/tgstation/pull/49661](url) - Carp Nerf, apart of the carp ided saga of anne prs

[https://github.com/tgstation/tgstation/pull/49524](url) - Carp rework, Was literally made to stop FOTNS gloves from working with carp, also ided

[https://github.com/tgstation/tgstation/pull/49103](url) - Krav rework, its now a actual martial art instead of buttons, I dislike this as Wardens are not nearly as OP as fuck in their autism cage as they should be

[https://github.com/tgstation/tgstation/pull/54146](url) - Hijack rework, > Port from citadel

[https://github.com/tgstation/tgstation/pull/50290](url) - Bags of holding need a Bluespace anomaly core now, This is stupid, they already locked you out of teleportation and were in general kinda dangerous to have.

That is it for now ill update this if anyone gives me more.
ided

**Comment by Nigkgro99** [comment]
I exclusively got a github just so I can upvote PR's like this. In the future, could you look into reverting medical or atleast adding cloners back? I really do hope more of the oldfags start making githubs

**Comment by Ty-the-Smonk** [comment]
> I exclusively got a github just so I can upvote PR's like this. In the future, could you look into reverting medical or atleast adding cloners back? I really do hope more of the oldfags start making githubs

Buddy, I'm not reverting shit, this is the issues tab of github, not pull requests, I just threw this in here for Null to look at.

**Comment by Nigkgro99** [comment]
> Buddy, I'm not reverting shit, this is the issues tab of github, not pull requests, I just threw this in here for Null to look at.

Buddy, I'm new to github, give me a fucking break

**Comment by Ty-the-Smonk** [comment]
No

**Comment by enthethan** [comment]
whats the PR that made explosives impotent

**Comment by enthethan** [comment]
revert chemical explosion nerf

**Comment by jaw-sh** [comment]
Interested mostly in reverting the Yellow Slime nerf and the Cargo Bounty removal. I did like Devils but it was kinda garbage, so maybe something down the line can be added in its place.

**Comment by jaw-sh** [comment]
Open an issue for individual requests. I do intend to restore Cargo and the Slime Battery. I'm personally soypilled on the stun question. I rage super hard at stuns in every game.
