### ISSUE TITLE
custom map?

### ISSUE THREAD

**Issue by Nigkgro99** [jaw-sh/tgstation#8]
I've always wanted to dive into mapping and I would love to make a custom map for this server, I am thinking of making a simple classic map that is just better than the others, or maybe even making a map with a very military/industrial half-life feel, I would also be open to other ideas. I'll keep this place posted with progress via pictures of my mapping

**Comment by jaw-sh** [comment]
I was thinking if anything we could adopt Delta or IceBox as the Kiwi Map. I like Delta, but for some reason /tg/ maintainers pass over it.
